axes:
  A:
    button: 3
    has_brake: true
    speed: 10
  B:
    button: 4
    has_brake: true
    speed: 10
  C:
    button: 5
    has_brake: false
    speed: 2000
  D:
    button: 6
    has_brake: false
    speed: 2000
  X:
    button: 0
    has_brake: true
    speed: 300
  Y:
    button: 1
    has_brake: true
    speed: 4
  Z:
    button: 2
    has_brake: true
    speed: 150
box_positions:
  box_1:
    A: -155.502075
    B: 49.7808
    C: -55.799999
    D: 3925.799805
    X: 636.299988
    Y: 33.672001
    Z: -12.852564
  box_2:
    A: -101.937271
    B: 51.760799
    C: -439.199982
    D: 3925.799805
    X: 636.299988
    Y: 33.700802
    Z: -12.852564
  box_3:
    A: -195.848953
    B: 49.3992
    C: -1576.799927
    D: 3925.799805
    X: 636.299988
    Y: 33.672001
    Z: -12.852564
  box_4: null
  box_5: null
buttons:
  brake_modifier: dpad_left
  direction_modifier: 7
  enable_modifier: dpad_up
  estop: 8
  go_home: 9
  save_home: 13
home_positions:
  A: -104.496956
  B: 49.082401
  C: -57.599998
  D: 3925.799805
  X: 636.265015
  Y: 100.900803
  Z: -12.852564
joystick:
  connection: auto
serial:
  baudrate: 115200
  port: /dev/ttyACM2
  timeout: 1.0
