axes:
  A:
    button: 3
    has_brake: true
    speed: 5
  B:
    button: 4
    has_brake: true
    speed: 2
  C:
    button: 5
    has_brake: false
    speed: 5
  D:
    button: 6
    has_brake: false
    speed: 0.002
  X:
    button: 0
    has_brake: true
    speed: 100
  Y:
    button: 1
    has_brake: true
    speed: 2
  Z:
    button: 2
    has_brake: true
    speed: 2
buttons:
  brake_modifier: dpad_left
  direction_modifier: 7
  enable_modifier: dpad_up
  estop: 8
  go_home: 9
  save_home: 13
home_positions:
  A: 6.809599
  B: -1.404
  C: 0.0
  D: 0.0
  X: 59.57
  Y: -2.2128
  Z: 5.048077
joystick:
  connection: auto
serial:
  baudrate: 115200
  port: /dev/ttyACM2
  timeout: 1.0
